// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
<<<<<<< HEAD
=======

>>>>>>> 5bad46d09911a7c1a88cc5fbc35715db6c15ed67
dotenv.config();
import { defineConfig } from "prisma/config";



export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
